blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name ='blog-home'),
    path('about/', views.about, name ='blog-about'),
]

financial_aid/urls.py
from django.contrib import admin
from django.urls import path , include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    path('', include('scholarship.urls')),
    
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scholarship/urls.py
from django.urls import path
from . import views

app_name = "aid"

urlpatterns = [
    path('', views.index, name='scholarship-categories'),
    path('category/<int:category_id>', views.scholarships,
         name='scholarship-categories-items'),
    path('category/<int:category_id>/item/<int:item_id>',
         views.item, name='scholarship-item'),
    path('applications', views.applications, name='scholarship-applications'),
    path('applications/classify', views.classify,
         name='scholarship-applications-classify'),
    path('send-message/', views.sendMessage, name='send_message'),
]

scholarship/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Category (models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

class Scholarship (models.Model):
    title = models.CharField(max_length=100)
    status = models.CharField(max_length=10)
    institution = models.CharField(max_length=100)
    description = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    # author = models.ForeignKey(User,on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.title

class Application (models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
    scholarship = models.ForeignKey(Scholarship, on_delete=models.PROTECT, null=True)
    accepted = models.BooleanField(null=True)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.user.username} {self.scholarship.title}'

scholarship/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.shortcuts import redirect
from django.core.exceptions import PermissionDenied
from .logistic_regression import classify as lr
from .message import send_sms
from django.http import JsonResponse
from users.models import Profile

# third-party import
import csv

# local imports
from .models import Category, Scholarship, Application
# Create your views here.


@login_required
def index(request):
    context = {
        'categories': Category.objects.all()
    }
    return render(request, 'scholarship/index.html', context)


def homepage(request):
    return render(request, 'scholarship/base.html')


@login_required
def scholarships(request, category_id):
    context = {
        'category': Category.objects.get(id=category_id),
        'scholarships': Scholarship.objects.filter(category=category_id)
    }
    return render(request, 'scholarship/scholarships.html', context)


@login_required
def item(request, category_id, item_id):
    scholarship = Scholarship.objects.get(id=item_id)
    applications = scholarship.application_set.filter(user=request.user)

    if request.method == 'POST':
        if applications.count():
            applications.delete()
            application = None
        else:
            application = Application(
                user=request.user, scholarship=scholarship)
            application.save()
    else:
        application = applications.first

    context = {
        'scholarship': scholarship,
        'application': application
    }
    return render(request, 'scholarship/item.html', context)


@login_required
def applications(request):
    accepted = Application.objects.filter(accepted=True)
    rejected = Application.objects.filter(accepted=False)
    pending = Application.objects.filter(accepted__isnull=True)

    if not request.user.is_staff:
        accepted = accepted.filter(user=request.user)
        rejected = rejected.filter(user=request.user)
        pending = pending.filter(user=request.user)

    context = {
        'accepted': accepted,
        'rejected': rejected,
        'pending': pending,
    }
    return render(request, 'scholarship/applications.html', context)


@login_required
def classify(request):
    if not request.user.is_staff:
        raise PermissionDenied

    if request.method == 'POST':
        # header = ['id', 'first_name', 'last_name', 'email',
        #           'gender', 'sponsor', 'background', 'aid']
        
        header =  ['id','sponsor','disabled','refugee_or_immigrant','family_background','KCSE','KCPE','aid','county', 'extra-curricular','leadership']
        
        
        data = []

        pending = Application.objects.filter(accepted__isnull=True)

        for application in pending:
            data.append(
                [application.id,
                 application.user.profile.sponsor,
                 application.user.profile.disabled,
                 application.user.profile.refugee_or_immigrant,
                 application.user.profile.background, 
                 application.user.profile.kcse,
                 application.user.profile.kcpe,
                 application.scholarship.category.title,
                 application.user.profile.county,
                 application.user.profile.extra_curricular,
                 application.user.profile.leadership,
                 ]
            )

        with open(f'{settings.MEDIA_ROOT}/data/pending.csv', 'w', encoding='UTF8') as f:
            writer = csv.writer(f)

            # write the header
            writer.writerow(header)

            # write the data
            writer.writerows(data)

        lr(f'{settings.MEDIA_ROOT}/data/')

        with open(f'{settings.MEDIA_ROOT}/data/outputs.csv', newline='') as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                # print(row['id'], row['accepted'])
                application = Application.objects.get(id=row['id'])
                if row['accepted'] == '1':
                    application.accepted = True
                else:
                    application.accepted = False
                application.save()

    return redirect('aid:scholarship-applications')


def sendMessage(request):
    if request.method == 'POST':
        profile_id = request.POST.get('profile_id')
        profile = Profile.objects.get(id=profile_id)
        # Call the send_message function
        name = profile.user.username  # Replace with actual field name
        number = profile.number  # Replace with actual field name

        application_id = request.POST.get('application_id')
        application = Application.objects.get(id=application_id)
        application_type = application.scholarship.title

        if application.accepted == True:
            message = f"Hi {name} this is financial aid. Your Application for {application_type} has been approved and the funds will be dispersed."
            send_sms.sending(number, name, message)
        else:
            message = f"Hi {name} this is financial aid. Your Application for {application_type} has been declined."
            send_sms.sending(number, name, message)

        # Return a JSON response with the message
        return JsonResponse({'message': 'message sent'})

    return JsonResponse({'error': 'Invalid request method'})

scholarship/templates/scholarship/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="{% static 'ingenious/css/fontawesome-free-5.15.4-web/css/all.css' %}">

    <link rel="stylesheet" href="{% static 'ingenious/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'ingenious/css/navigation.css' %}">
    <link rel="stylesheet" href="{% static 'ingenious/css/theme-switch.css' %}">
    <link rel="stylesheet" href="{% static 'ingenious/css/buttons.css' %}">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Raleway&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Abel&display=swap');

        *{
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        body{
            font-family: var(--text-font), sans-serif;
            /* background: #414141; */
            background-color: var(--bg-color);
            color: var(--font-color);
        }

        [data-theme="dark"] .light-visible{
            display: none;
        }

        .dark-visible {
            display: none;
        }
        [data-theme="dark"] .dark-visible{
            display: block;
        }
        
        .big-container{
            max-width: 1600px;
            margin: 0 auto;
            padding: 0 1.5rem;
        }

        .container{
            max-width: 1280px;
            margin: 0 auto;
            padding: 0 1.5rem;
        }

        .small-container{
            {% comment %} max-width: 1080px; {% endcomment %}
            margin: 0 auto;
            padding: 0 1.5rem;
        }

        .nav-links.active {
            background: var(--bg-color);
            color: var(--font-color);
        }

        .nav-links ul li a {
            font-family: var(--title-font);
        }

        header {
            height: 40vh;
            width: 100%;
            background: url('/static/ingenious/img/clarisse-meyer-jKU2NneZAbI-unsplash.jpg');
            background-repeat: no-repeat;
            background-size: cover;
        }

        header .wrapper{
            height: 100%;
            width: 100%;
            padding: 20px;
            display: flex;
            align-items: center;
            background: rgba(0, 0, 0, 0.661);
        }

        header h2{
            font-family: var(--title-font), sans-serif;
        }
    
        .item-list{
            display: grid;
            column-gap: 20px;
            grid-template-columns: repeat(1, 1fr);
        }

        @media (min-width: 992px) {
            .item-list{
                grid-template-columns: repeat(4, 1fr);
            }
        }

        .item-list .item{
            height: 60px;
            background: var(--card-bg-color);
            box-shadow: 0 5px 14px rgba(0,0,0,0.2);
            border-radius: 10px 0;
            margin: 20px 0;
        }

        .item-list .item a{
            display: flex;
            justify-content: space-between;
            align-items; center;
            padding: 20px;
            font-family: var(--title-font), sans-serif;
            text-transform: uppercase;
            color: var(--card-font-color);
        }

        .item-list .item:hover a{
            color: rgb(133, 133, 133);
        }

        .item-list .item h3{
            {% comment %} margin-bottom: 30px; {% endcomment %}
        }

        .item-list .item .details {
            font-family: var(--title-font), sans-serif;
            display: flex;
            align-items: center;
            justify-content: flex-end;
        }

        .item-list .item .details i{
            background: var(--card-font-color);
            color: var(--card-bg-color);
            height: 25px;
            width: 25px;
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 50%;
            margin-right: 10px;
        }

        .item-list .item span{
            font-family: 'Abel', sans-serif;
            background: var(--bg-color);
            color: var(--card-color);
            border-radius: 30px;
            padding: 0 10px;
        }

        .item-list .item span.open{
            color: rgb(0, 128, 0);
            border-color: rgb(0, 128, 0);
        }

        .item-list .item span.closed{
            color: rgb(255, 0, 0);
            border-color: rgb(255, 0, 0);
        }

        @media (max-width: 768px) {
            .xs-hidden {
                display: none !important;
            }
        }
        .main-content{
            height: 100vh;
            padding: 10px;
        }
        .sub-main-content{
            width:100%;
            display: grid;
            grid-template-columns: 4.5fr 1.55fr;
            grid-column-gap: 10px;
            padding: 0 0 0 30px;
        }
        .left-side{
            
        }
        .right-side{
            padding: 0 30px 10px 10px;
            
        }
        .category-items{
            display: flex;
            flex-direction:column;
            gap: 10px;
        }
        .category-item{
            border-bottom: 1px solid gray;
            padding: 10px 15px;

        }
    </style>
</head>
<body>
    <div class="big-container" style="padding: 0; ">
        <header>
            <!-- navbar -->
            <nav>
                <!-- <div class="bg">
                    <img src="static/kitukizuri/img/ingenious-bg.png" alt="" />
                </div> -->
                <a href="{% url 'aid:scholarship-categories'%}" class="logo" style="background: white; z-index: 99999; margin-left: 30px;">
                    <img src="scholarship/static/ingenious/img/logo.png" alt="">
                </a>
                <div class="fas menu-toggle"></div>
                <div class="nav-links">
                <ul>
                    <li><a href="/">HOME</a></li>
                    {% comment %} <li><a href="/about">ABOUT</a></li> {% endcomment %}
                    <li><a href="{% url 'profile'%}">PROFILE</a></li>
<!--                    <li><a href="#">CONTACT</a></li>-->
                </ul>
                <input type="checkbox" id="theme-switch">
                <label for="theme-switch" class="switch">
                    <div class="toggle"></div>
                    <div class="names">
                        <p class="light">Light</p>
                        <p class="dark">Dark</p>
                    </div>
                </label>
                <!-- <a class="cta" href="/test/donate.html"><button>Donate</button></a> -->
                </div>
            </nav>
            <!-- end of navbar -->
            <div class="wrapper">
                <div style="flex: 50%; display: flex; justify-content: center;">
                    <div style="border-radius: 10px; max-width: 600px;" class="xs-margin-top-10">
                        <div style="padding: 30px; color: white; border-radius: 10px; position: relative; z-index: 1;">
                            <div class="bg" style="opacity: 0.2">
                                <img src="static/img/bg.png" style="object-fit: contain;" alt="">
                            </div>
                            <h2 style="color: #1DA1F1; margin-bottom: 10px;">WE ARE HERE TO HELP</h2>
                            <p>Let's get this over with already. You are looking for help and we are lookinng to help.
                                Great!
                                So take a look down below for opportunties you would be interested in and... <br>
                                APPLY for it.</p>
                        </div>
                    </div>
                </div>
                <div class="xs-hidden" style="flex: 50%;">

                </div>
            </div>
        </header>
    </div>
    <div class="small-container">
        <ul class="item-list">
            {% for category in categories %}
            <li class="item">
                <a href="{% url 'aid:scholarship-categories-items' category.id %}">
                    <h3>{{category.title}}</h3>
                    <div class="details">
                        <div>
                            <span class="open">
                                {{category.scholarship_set.all.count}}
                            </span>
                        </div>
                    </div>
                </a>
            </li>
            {% endfor %}
            <li class="item">
                <a href="{% url 'aid:scholarship-applications' %}">
                    <h3>applications</h3>
                </a>
            </li>
        </ul>
    </div>
    <div class="main-content">
        <div class="sub-main-content">
            <div class="left-side">
               {% lorem 4 p random %}
            </div>
            <div class="right-side">
                <div class="category-items">
                    <div class="category-item">Library Service Portal</div>
                    <div class="category-item">Student Management System</div>
                    <div class="category-item">Games and Sports</div>
                    <div class="category-item">Security & Safety Services</div>
                    <div class="category-item">Students Welfare Authority (SWA)</div>
                    <div class="category-item">University Health Services (UHS)</div>
                </div>
            </div>
            </div
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <script src="{% static 'ingenious/js/main.js' %}"></script>
    <script src="{% static 'ingenious/js/theme-switch.js' %}"></script>
</body>
</html>

scholarship/templates/scholarship/scholarships.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="{% static 'ingenious/css/fontawesome-free-5.15.4-web/css/all.css' %}">

    <link rel="stylesheet" href="{% static 'ingenious/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'ingenious/css/navigation.css' %}">
    <link rel="stylesheet" href="{% static 'ingenious/css/theme-switch.css' %}">
    <link rel="stylesheet" href="{% static 'ingenious/css/buttons.css' %}">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Raleway&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Abel&display=swap');

        *{
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        body{
            font-family: var(--text-font), sans-serif;
            /* background: #414141; */
            background-color: var(--bg-color);
            color: var(--font-color);
        }

        [data-theme="dark"] .light-visible{
            display: none;
        }

        .dark-visible {
            display: none;
        }
        [data-theme="dark"] .dark-visible{
            display: block;
        }
        
        .big-container{
            max-width: 1600px;
            margin: 0 auto;
            padding: 0 1.5rem;
        }

        .container{
            max-width: 1280px;
            margin: 0 auto;
            padding: 0 1.5rem;
        }

        .small-container{
            max-width: 1080px;
            margin: 0 auto;
            padding: 0 1.5rem;
        }

        .nav-links.active {
            background: var(--bg-color);
            color: var(--font-color);
        }

        .nav-links ul li a {
            font-family: var(--title-font);
        }

        header {
            height: 40vh;
            width: 100%;
            background: url('/static/ingenious/img/clarisse-meyer-jKU2NneZAbI-unsplash.jpg');
            background-repeat: no-repeat;
            background-size: cover;
        }

        header .wrapper{
            height: 100%;
            width: 100%;
            padding: 20px;
            display: flex;
            align-items: center;
            background: rgba(0, 0, 0, 0.661);
        }

        header h2{
            font-family: var(--title-font), sans-serif;
        }
    
        .item-list{

        }

        .item-list .item{
            background: var(--card-bg-color);
            box-shadow: 0 5px 14px rgba(0,0,0,0.2);
            border-radius: 30px 0;
            margin: 20px 0;
        }

        .item-list .item a{
            display: block;
            padding: 20px;
            color: var(--card-font-color);
        }

        .item-list .item:hover a{
            color: rgb(133, 133, 133);
        }

        .item-list .item h3{
            margin-bottom: 7px;
        }

        .item-list .item .details {
            font-family: var(--title-font), sans-serif;
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .item-list .item .details i{
            background: var(--card-font-color);
            color: var(--card-bg-color);
            height: 25px;
            width: 25px;
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 50%;
            margin-right: 10px;
        }

        .item-list .item span{
            font-family: 'Abel', sans-serif;
            border: 1px solid grey;
            border-radius: 30px;
            padding: 0 10px;
        }

        .item-list .item span.open{
            color: rgb(0, 128, 0);
            border-color: rgb(0, 128, 0);
        }

        .item-list .item span.closed{
            color: rgb(255, 0, 0);
            border-color: rgb(255, 0, 0);
        }

        @media (max-width: 768px) {
            .xs-hidden {
                display: none !important;
            }
        }
    </style>
</head>
<body>
    <div class="big-container" style="padding: 0; ">
        <header>
            <!-- navbar -->
            <nav>
                <!-- <div class="bg">
                    <img src="static/kitukizuri/img/ingenious-bg.png" alt="" />
                </div> -->
                <a href="{% url 'aid:scholarship-categories'%}" class="logo">
                    <h3>Scholarship</h3>
                    <!-- <img src="static/img/ingenious.png" alt=""> -->
                </a>
                <div class="fas menu-toggle"></div>
                <div class="nav-links">
                <ul>
                    <li><a href="/">HOME</a></li>
                    {% comment %} <li><a href="/about">ABOUT</a></li> {% endcomment %}
                    <li><a href="{% url 'profile'%}">PROFILE</a></li>
<!--                    <li><a href="#">CONTACT</a></li>-->
                </ul>
                <input type="checkbox" id="theme-switch">
                <label for="theme-switch" class="switch">
                    <div class="toggle"></div>
                    <div class="names">
                        <p class="light">Light</p>
                        <p class="dark">Dark</p>
                    </div>
                </label>
                <!-- <a class="cta" href="/test/donate.html"><button>Donate</button></a> -->
                </div>
            </nav>
            <!-- end of navbar -->
            <div class="wrapper">
                <div style="flex: 50%; display: flex; justify-content: center;">
                    <div style="border-radius: 10px; max-width: 600px;" class="xs-margin-top-10">
                        <div style="padding: 30px; color: white; border-radius: 10px; position: relative; z-index: 1;">
                            <div class="bg" style="opacity: 0.2">
                                <img src="static/img/bg.png" style="object-fit: contain;" alt="">
                            </div>
                            <h2 style="color: #1DA1F1; margin-bottom: 10px; text-transform: uppercase;">{{category.title}}</h2>
                        </div>
                    </div>
                </div>
                <div class="xs-hidden" style="flex: 50%;">

                </div>
            </div>
        </header>
    </div>
    <div class="small-container">
        <ul class="item-list">
            {% for scholarship in scholarships %}
            <li class="item">
                <a href="{% url 'aid:scholarship-item' category.id scholarship.id %}">
                    <h3>{{scholarship.title}}</h3>
                    <div class="details">
                        <div>
                            <span class="open">
                                {{scholarship.status}}
                            </span>
                        </div>
                        <div style="display: flex; align-items: center; margin-right: 10px;">
                            <i class="fas fa-university"></i>
                            {{scholarship.institution}}
                        </div>
                    </div>
                </a>
            </li>
            {% endfor %}
<!--            <li class="item">-->
<!--                <a href="item.html">-->
<!--                    <h3>Some random scholarship from I do not know where</h3>-->
<!--                    <div class="details">-->
<!--                        <div>-->
<!--                            <span class="closed">-->
<!--                                CLOSED-->
<!--                            </span>-->
<!--                        </div>-->
<!--                        <div style="display: flex; align-items: center; margin-right: 10px;">-->
<!--                            <i class="fas fa-university"></i>-->
<!--                            University of Nairobi-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="item">-->
<!--                <a href="item.html">-->
<!--                    <h3>Some random scholarship from I do not know where</h3>-->
<!--                    <div class="details">-->
<!--                        <div>-->
<!--                            <span class="open">-->
<!--                                OPEN-->
<!--                            </span>-->
<!--                        </div>-->
<!--                        <div style="display: flex; align-items: center; margin-right: 10px;">-->
<!--                            <i class="fas fa-university"></i>-->
<!--                            University of Nairobi-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="item">-->
<!--                <a href="item.html">-->
<!--                    <h3>Some random scholarship from I do not know where</h3>-->
<!--                    <div class="details">-->
<!--                        <div>-->
<!--                            <span class="open">-->
<!--                                OPEN-->
<!--                            </span>-->
<!--                        </div>-->
<!--                        <div style="display: flex; align-items: center; margin-right: 10px;">-->
<!--                            <i class="fas fa-university"></i>-->
<!--                            University of Nairobi-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="item">-->
<!--                <a href="item.html">-->
<!--                    <h3>Some random scholarship from I do not know where</h3>-->
<!--                    <div class="details">-->
<!--                        <div>-->
<!--                            <span class="open">-->
<!--                                OPEN-->
<!--                            </span>-->
<!--                        </div>-->
<!--                        <div style="display: flex; align-items: center; margin-right: 10px;">-->
<!--                            <i class="fas fa-university"></i>-->
<!--                            University of Nairobi-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </a>-->
<!--            </li>-->
        </ul>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <script src="{% static 'ingenious/js/main.js' %}"></script>
    <script src="{% static 'ingenious/js/theme-switch.js' %}"></script>
</body>
</html>